owner: nicolastorgato
repo: upptime

sites:
  - name: Sito Istituzionale Provincia di Treviso
    url: https://www.provincia.treviso.it
  - name: Amministrazione Trasparente Provincia di Treviso
    url: https://amministrazionetrasparente.provincia.treviso.it/L190/
  - name: Istanze Online Provincia di Treviso
    url: https://servizi.provincia.treviso.it/

